vich_uploader:
    db_driver: orm

    mappings:
        user_profil_picture:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
        article_image:
           uri_prefix: /images/imgarticle
           upload_destination: '%kernel.project_dir%/public/images/imgarticle'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
