# index:
#    path: /
#    controller: App\Controller\DefaultController::index
#----ROUTES STATIQUES-----#
app_mentions_legales:
  path: /mentionslegales
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pagesstatiques/mentionslegales.html.twig
app_pol_confidentialite:
  path: /politique/confidentialite
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pagesstatiques/polconfidentialite.html.twig